/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package auto.recharge.system;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author monirozzamanroni
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        bg = new javax.swing.JPanel();
        nevPanel = new javax.swing.JPanel();
        nevItemOne = new javax.swing.JPanel();
        homeLabel = new javax.swing.JLabel();
        homeTextLabel = new javax.swing.JLabel();
        nevItemOne2 = new javax.swing.JPanel();
        homeLabel2 = new javax.swing.JLabel();
        homeTextLabel2 = new javax.swing.JLabel();
        nevItemOne3 = new javax.swing.JPanel();
        homeLabel3 = new javax.swing.JLabel();
        homeTextLabel3 = new javax.swing.JLabel();
        nevItemOne4 = new javax.swing.JPanel();
        homeLabel4 = new javax.swing.JLabel();
        homeTextLabel4 = new javax.swing.JLabel();
        nevItemOne5 = new javax.swing.JPanel();
        homeLabel5 = new javax.swing.JLabel();
        homeTextLabel5 = new javax.swing.JLabel();
        appName = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        getNumberPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        getMobileNumber = new javax.swing.JTextField();
        preOrPostCheck = new javax.swing.JComboBox<>();
        amount = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        send = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        statusTable = new javax.swing.JTable();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 0));

        nevPanel.setBackground(new java.awt.Color(80, 55, 145));

        nevItemOne.setBackground(new java.awt.Color(136, 107, 212));

        homeLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        homeLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        homeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/home_icon.png"))); // NOI18N

        homeTextLabel.setBackground(new java.awt.Color(255, 255, 255));
        homeTextLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        homeTextLabel.setForeground(new java.awt.Color(255, 255, 255));
        homeTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeTextLabel.setText("Home");

        javax.swing.GroupLayout nevItemOneLayout = new javax.swing.GroupLayout(nevItemOne);
        nevItemOne.setLayout(nevItemOneLayout);
        nevItemOneLayout.setHorizontalGroup(
            nevItemOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nevItemOneLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(homeLabel)
                .addGap(42, 42, 42)
                .addComponent(homeTextLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        nevItemOneLayout.setVerticalGroup(
            nevItemOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nevItemOneLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(nevItemOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(homeLabel)
                    .addComponent(homeTextLabel))
                .addGap(24, 24, 24))
        );

        nevItemOne2.setBackground(new java.awt.Color(97, 77, 148));

        homeLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        homeLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        homeLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/home_icon.png"))); // NOI18N

        homeTextLabel2.setBackground(new java.awt.Color(255, 255, 255));
        homeTextLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        homeTextLabel2.setForeground(new java.awt.Color(255, 255, 255));
        homeTextLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeTextLabel2.setText("My Balence");

        javax.swing.GroupLayout nevItemOne2Layout = new javax.swing.GroupLayout(nevItemOne2);
        nevItemOne2.setLayout(nevItemOne2Layout);
        nevItemOne2Layout.setHorizontalGroup(
            nevItemOne2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nevItemOne2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(homeLabel2)
                .addGap(42, 42, 42)
                .addComponent(homeTextLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        nevItemOne2Layout.setVerticalGroup(
            nevItemOne2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nevItemOne2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(nevItemOne2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(homeLabel2)
                    .addComponent(homeTextLabel2))
                .addGap(24, 24, 24))
        );

        nevItemOne3.setBackground(new java.awt.Color(97, 77, 148));

        homeLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        homeLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        homeLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/home_icon.png"))); // NOI18N

        homeTextLabel3.setBackground(new java.awt.Color(255, 255, 255));
        homeTextLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        homeTextLabel3.setForeground(new java.awt.Color(255, 255, 255));
        homeTextLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeTextLabel3.setText("My Reseller");

        javax.swing.GroupLayout nevItemOne3Layout = new javax.swing.GroupLayout(nevItemOne3);
        nevItemOne3.setLayout(nevItemOne3Layout);
        nevItemOne3Layout.setHorizontalGroup(
            nevItemOne3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nevItemOne3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(homeLabel3)
                .addGap(42, 42, 42)
                .addComponent(homeTextLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        nevItemOne3Layout.setVerticalGroup(
            nevItemOne3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nevItemOne3Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(nevItemOne3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(homeLabel3)
                    .addComponent(homeTextLabel3))
                .addGap(24, 24, 24))
        );

        nevItemOne4.setBackground(new java.awt.Color(97, 77, 148));

        homeLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        homeLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        homeLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/home_icon.png"))); // NOI18N

        homeTextLabel4.setBackground(new java.awt.Color(255, 255, 255));
        homeTextLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        homeTextLabel4.setForeground(new java.awt.Color(255, 255, 255));
        homeTextLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeTextLabel4.setText("Add Package & Offer");

        javax.swing.GroupLayout nevItemOne4Layout = new javax.swing.GroupLayout(nevItemOne4);
        nevItemOne4.setLayout(nevItemOne4Layout);
        nevItemOne4Layout.setHorizontalGroup(
            nevItemOne4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nevItemOne4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(homeLabel4)
                .addGap(42, 42, 42)
                .addComponent(homeTextLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        nevItemOne4Layout.setVerticalGroup(
            nevItemOne4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nevItemOne4Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(nevItemOne4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(homeLabel4)
                    .addComponent(homeTextLabel4))
                .addGap(24, 24, 24))
        );

        nevItemOne5.setBackground(new java.awt.Color(97, 77, 148));

        homeLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        homeLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        homeLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/home_icon.png"))); // NOI18N

        homeTextLabel5.setBackground(new java.awt.Color(255, 255, 255));
        homeTextLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        homeTextLabel5.setForeground(new java.awt.Color(255, 255, 255));
        homeTextLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeTextLabel5.setText("Settings");

        javax.swing.GroupLayout nevItemOne5Layout = new javax.swing.GroupLayout(nevItemOne5);
        nevItemOne5.setLayout(nevItemOne5Layout);
        nevItemOne5Layout.setHorizontalGroup(
            nevItemOne5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nevItemOne5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(homeLabel5)
                .addGap(42, 42, 42)
                .addComponent(homeTextLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        nevItemOne5Layout.setVerticalGroup(
            nevItemOne5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nevItemOne5Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(nevItemOne5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(homeLabel5)
                    .addComponent(homeTextLabel5))
                .addGap(24, 24, 24))
        );

        appName.setFont(new java.awt.Font("Cambria Math", 3, 36)); // NOI18N
        appName.setForeground(new java.awt.Color(255, 255, 255));
        appName.setText("Auto Recharge");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator2.setForeground(new java.awt.Color(252, 136, 136));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("System");

        javax.swing.GroupLayout nevPanelLayout = new javax.swing.GroupLayout(nevPanel);
        nevPanel.setLayout(nevPanelLayout);
        nevPanelLayout.setHorizontalGroup(
            nevPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nevItemOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(nevItemOne2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(nevItemOne3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(nevItemOne4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(nevItemOne5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(nevPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(nevPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nevPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(appName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nevPanelLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(39, 39, 39)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        nevPanelLayout.setVerticalGroup(
            nevPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nevPanelLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(appName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nevPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nevPanelLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nevPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(nevItemOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nevItemOne2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nevItemOne3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nevItemOne4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nevItemOne5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getNumberPanel.setBackground(new java.awt.Color(142, 119, 245));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mobile No :");

        getMobileNumber.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        preOrPostCheck.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        preOrPostCheck.setForeground(new java.awt.Color(255, 255, 255));
        preOrPostCheck.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prepaid", "Postpaid" }));

        amount.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        amount.setText("100");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 X", "2 X", "3 X", "4 X" }));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Amount :");

        send.setBackground(new java.awt.Color(153, 255, 0));
        send.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        send.setText("Send");

        clear.setBackground(new java.awt.Color(255, 102, 102));
        clear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        clear.setText("Clear all");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout getNumberPanelLayout = new javax.swing.GroupLayout(getNumberPanel);
        getNumberPanel.setLayout(getNumberPanelLayout);
        getNumberPanelLayout.setHorizontalGroup(
            getNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(getNumberPanelLayout.createSequentialGroup()
                .addGroup(getNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(getNumberPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(getNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(getNumberPanelLayout.createSequentialGroup()
                                .addComponent(getMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(getNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(preOrPostCheck, 0, 130, Short.MAX_VALUE)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, getNumberPanelLayout.createSequentialGroup()
                                .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addGroup(getNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(send, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(getNumberPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(getNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        getNumberPanelLayout.setVerticalGroup(
            getNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(getNumberPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGroup(getNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(getNumberPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(getMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(getNumberPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(preOrPostCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(getNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(getNumberPanelLayout.createSequentialGroup()
                        .addComponent(send, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        statusTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Phone No.", "Amount", "Status", "Date & Time", "Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(statusTable);
        if (statusTable.getColumnModel().getColumnCount() > 0) {
            statusTable.getColumnModel().getColumn(0).setResizable(false);
            statusTable.getColumnModel().getColumn(1).setResizable(false);
            statusTable.getColumnModel().getColumn(2).setResizable(false);
            statusTable.getColumnModel().getColumn(3).setResizable(false);
            statusTable.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(nevPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(getNumberPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nevPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(getNumberPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Properties properties= new Properties();
                try {
                    properties.load(new FileReader("src\\resources\\config.properties"));
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }
                Home home = new Home();
                home.setVisible(true);
                home.setExtendedState(JFrame.MAXIMIZED_BOTH);
                home.setTitle(properties.getProperty("appName"));
                home.setIconImage(new ImageIcon("images/auto_r_s_icon.png").getImage());
               // appTitle.setHorizontalAlignment(JLabel.LEFT);
                //appTitle.setText("<html><font color='red'>A</font>uto <font color='red'>R</font>echarge <font color='red'>S</font>ystem</html>");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount;
    private javax.swing.JLabel appName;
    private javax.swing.JPanel bg;
    private javax.swing.JButton clear;
    private javax.swing.JTextField getMobileNumber;
    private javax.swing.JPanel getNumberPanel;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JLabel homeLabel1;
    private javax.swing.JLabel homeLabel2;
    private javax.swing.JLabel homeLabel3;
    private javax.swing.JLabel homeLabel4;
    private javax.swing.JLabel homeLabel5;
    private javax.swing.JLabel homeTextLabel;
    private javax.swing.JLabel homeTextLabel1;
    private javax.swing.JLabel homeTextLabel2;
    private javax.swing.JLabel homeTextLabel3;
    private javax.swing.JLabel homeTextLabel4;
    private javax.swing.JLabel homeTextLabel5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel nevItemOne;
    private javax.swing.JPanel nevItemOne1;
    private javax.swing.JPanel nevItemOne2;
    private javax.swing.JPanel nevItemOne3;
    private javax.swing.JPanel nevItemOne4;
    private javax.swing.JPanel nevItemOne5;
    private javax.swing.JPanel nevPanel;
    private javax.swing.JComboBox<String> preOrPostCheck;
    private javax.swing.JButton send;
    private javax.swing.JTable statusTable;
    // End of variables declaration//GEN-END:variables
}
