/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package auto.recharge.system;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author monirozzamanroni
 */
public class MobileBankingBalanceShowCard extends javax.swing.JPanel {

    /**
     * Creates new form MobileBankingBalanceShowCard
     */
    public MobileBankingBalanceShowCard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ammountShowCard = new javax.swing.JPanel();
        serviceNameText = new javax.swing.JLabel();
        amountBalanceText = new javax.swing.JLabel();
        refrashBalanceBut = new javax.swing.JButton();
        lastUpdateTimeText = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ammountShowCard.setBackground(new java.awt.Color(204, 255, 204));

        serviceNameText.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        serviceNameText.setText("bKash");

        amountBalanceText.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        amountBalanceText.setForeground(new java.awt.Color(255, 0, 51));
        amountBalanceText.setText("10000 Tk");

        refrashBalanceBut.setBackground(new java.awt.Color(255, 0, 0));
        refrashBalanceBut.setForeground(new java.awt.Color(255, 255, 255));
        refrashBalanceBut.setText("Refrash");
        refrashBalanceBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refrashBalanceButActionPerformed(evt);
            }
        });

        lastUpdateTimeText.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lastUpdateTimeText.setForeground(new java.awt.Color(204, 0, 51));
        lastUpdateTimeText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lastUpdateTimeText.setText("Last update : 20/20/20 12:12 PM");

        javax.swing.GroupLayout ammountShowCardLayout = new javax.swing.GroupLayout(ammountShowCard);
        ammountShowCard.setLayout(ammountShowCardLayout);
        ammountShowCardLayout.setHorizontalGroup(
            ammountShowCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ammountShowCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ammountShowCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lastUpdateTimeText, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ammountShowCardLayout.createSequentialGroup()
                        .addComponent(serviceNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(amountBalanceText, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refrashBalanceBut, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        ammountShowCardLayout.setVerticalGroup(
            ammountShowCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ammountShowCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ammountShowCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serviceNameText)
                    .addComponent(amountBalanceText)
                    .addComponent(refrashBalanceBut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lastUpdateTimeText))
        );

        add(ammountShowCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void refrashBalanceButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refrashBalanceButActionPerformed
        System.out.println("auto.recharge.system.MobileBankingBalanceShowCard.refrashBalanceButActionPerformed()");
    }//GEN-LAST:event_refrashBalanceButActionPerformed

    public JLabel getAmountBalanceText() {
        return amountBalanceText;
    }

    public void setAmountBalanceText(JLabel amountBalanceText) {
        this.amountBalanceText = amountBalanceText;
    }

    public JLabel getLastUpdateTimeText() {
        return lastUpdateTimeText;
    }

    public void setLastUpdateTimeText(JLabel lastUpdateTimeText) {
        this.lastUpdateTimeText = lastUpdateTimeText;
    }

    public JButton getRefrashBalanceBut() {
        return refrashBalanceBut;
    }

    public void setRefrashBalanceBut(JButton refrashBalanceBut) {
        this.refrashBalanceBut = refrashBalanceBut;
    }

    public JLabel getServiceNameText() {
        return serviceNameText;
    }

    public void setServiceNameText(JLabel serviceNameText) {
        this.serviceNameText = serviceNameText;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ammountShowCard;
    private javax.swing.JLabel amountBalanceText;
    private javax.swing.JLabel lastUpdateTimeText;
    private javax.swing.JButton refrashBalanceBut;
    private javax.swing.JLabel serviceNameText;
    // End of variables declaration//GEN-END:variables
}
